[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
solc_version = "0.8.24"
gas_reports = ["*"]
optimizer = true
optimizer_runs = 200

[profile.test]
fuzz = { runs = 256 }

[profile.ci]
fuzz = { runs = 1000 }
invariant = { runs = 32, depth = 32 }
